# Generated by Django 5.2.5 on 2026-04-02 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_vehicleapplication_is_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleapplication',
            name='identifier',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicleapplication',
            name='role',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
