# Generated by Django 6.0.3 on 2026-04-03 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_vehicleapplication_identifier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleapplication',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
