# Generated by Django 6.0.3 on 2026-04-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_vehicleapplication_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleapplication',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehicleapplication',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
