# Generated by Django 5.2.5 on 2026-04-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_vehicleapplication_payment_method_and_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_username', models.CharField(max_length=100)),
                ('sticker_id', models.CharField(max_length=20)),
                ('reserved_spots', models.TextField()),
                ('reservation_reason', models.TextField()),
                ('reserved_for_datetime', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by_username', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
